site: nopcorn
url: https://nopcorn.run
domain: nopcorn.run
title: nopcorn
description: thoughts and ramblings of an offensive security engineer
permalink: pretty

author:
  name: nopcorn
  url: https://nopcorn.run

logo: /assets/logo.jpeg
twitter:
  username: nopcorn18785
  card: summary
social:
  name: nopcorn
  links:
    - https://github.com/nopcorn
    - https://x.com/nopcorn18785

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/logo.jpeg
      seo:
        type: BlogPosting
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /assets/logo.jpeg
